import type { Venue } from "@/lib/supabase/types";

/**
 * Mock venues for building UI before Supabase is connected.
 * Covers a range of categories, neighborhoods, and vibe tags.
 */
export const MOCK_VENUES: Venue[] = [
  {
    id: "v1",
    name: "The Rooftop at Pier 17",
    neighborhood: "Seaport",
    city: "nyc",
    lat: 40.7063,
    lng: -74.0024,
    category: "rooftop",
    google_place_id: "mock-1",
    vibe_tags: ["rooftop", "trendy", "date-night", "lively"],
    description: "Open-air rooftop with stunning views of the Brooklyn Bridge and East River. Live music nights and craft cocktails.",
    image_url: null,
    price_level: 3,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "v2",
    name: "Café Kitsuné",
    neighborhood: "West Village",
    city: "nyc",
    lat: 40.7336,
    lng: -74.0027,
    category: "cafe",
    google_place_id: "mock-2",
    vibe_tags: ["chill", "cozy", "trendy", "solo-friendly"],
    description: "Japanese-inspired coffee shop with matcha lattes and a curated vinyl selection. Perfect for working solo.",
    image_url: null,
    price_level: 2,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "v3",
    name: "House of Yes",
    neighborhood: "Bushwick",
    city: "nyc",
    lat: 40.7048,
    lng: -73.9235,
    category: "club",
    google_place_id: "mock-3",
    vibe_tags: ["rowdy", "creative", "late-night", "group-hang"],
    description: "Immersive nightlife with circus performers, themed parties, and a no-judgment dance floor.",
    image_url: null,
    price_level: 2,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "v4",
    name: "Cha Cha Matcha",
    neighborhood: "Nolita",
    city: "nyc",
    lat: 40.7228,
    lng: -73.9955,
    category: "cafe",
    google_place_id: "mock-4",
    vibe_tags: ["trendy", "casual", "solo-friendly", "creative"],
    description: "Instagrammable matcha bar with pink-and-green aesthetic. Great for a quick pick-me-up.",
    image_url: null,
    price_level: 1,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "v5",
    name: "Please Don't Tell",
    neighborhood: "East Village",
    city: "nyc",
    lat: 40.7264,
    lng: -73.9841,
    category: "bar",
    google_place_id: "mock-5",
    vibe_tags: ["hidden-gem", "intimate", "upscale", "date-night"],
    description: "Legendary speakeasy behind a phone booth inside a hot dog shop. Craft cocktails in a candlelit setting.",
    image_url: null,
    price_level: 3,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "v6",
    name: "Smorgasburg",
    neighborhood: "Williamsburg",
    city: "nyc",
    lat: 40.7216,
    lng: -73.9618,
    category: "market",
    google_place_id: "mock-6",
    vibe_tags: ["outdoor", "lively", "casual", "group-hang", "local"],
    description: "Brooklyn's legendary open-air food market. 100+ vendors serving everything from ramen burgers to Thai rolled ice cream.",
    image_url: null,
    price_level: 1,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "v7",
    name: "Le Crocodile",
    neighborhood: "Williamsburg",
    city: "nyc",
    lat: 40.7125,
    lng: -73.9577,
    category: "restaurant",
    google_place_id: "mock-7",
    vibe_tags: ["upscale", "romantic", "classic", "date-night"],
    description: "French brasserie with art deco interiors, oysters, and a killer steak frites. Special occasion energy.",
    image_url: null,
    price_level: 3,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "v8",
    name: "Brooklyn Boulders",
    neighborhood: "Greenpoint",
    city: "nyc",
    lat: 40.7284,
    lng: -73.9548,
    category: "gallery",
    google_place_id: "mock-8",
    vibe_tags: ["lively", "creative", "group-hang", "casual"],
    description: "Co-working meets climbing gym with community events, open mic nights, and a solid espresso bar.",
    image_url: null,
    price_level: 2,
    hours: null,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
];

/** Placeholder Neyece Scores (random 70-98 range) keyed by venue id. */
export const MOCK_SCORES: Record<string, number> = {
  v1: 94,
  v2: 91,
  v3: 87,
  v4: 82,
  v5: 96,
  v6: 78,
  v7: 89,
  v8: 75,
};

/** Mood → vibe tag mapping for filtering. */
export const MOOD_TAG_MAP: Record<string, string[]> = {
  All: [],
  Chill: ["chill", "cozy", "solo-friendly"],
  Lively: ["lively", "group-hang", "rowdy"],
  "Date Night": ["date-night", "romantic", "intimate"],
  "Late Night": ["late-night", "rowdy"],
  Outdoors: ["outdoor", "rooftop"],
  Creative: ["creative", "artsy"],
};

export const MOODS = Object.keys(MOOD_TAG_MAP);
